version: "3.3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8004
    volumes:
      - .:/code
    ports:
      - 8004:8000
    depends_on:
      - db
  traefik:
    image: traefik
  cadvisor:
    image: google/cadvisor
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  s12:
    build:
      context: ./dir
      dockerfile: Dockerfile
      args:
        buildno: 1
    configs:
      my_config:
        file: ./my_config.txt
      my_other_config:
        external: true
    cgroup_parent: m-executor-abcd
    cap_add: ALL
    cap_drop:
      - ALL
      - NET
    container_name: my_container
